require("ayuxh.set")
require("ayuxh.packer")
require("ayuxh.colorscheme")
require("ayuxh.remap")
require("ayuxh.toggleterm")
require("ayuxh.cmp")
require("ayuxh.mason")
require("ayuxh.lsp")
require("ayuxh.bufferline")
require("ayuxh.nvimtree")
require("ayuxh.telescope")
require("ayuxh.comment")
require("ayuxh.gitsigns")
require("ayuxh.gitblame")
-- require("ayuxh.lualine") Customize this later
